// <auto-generated />
using System;
using LeKatsuMNL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeKatsuMNL.Migrations
{
    [DbContext(typeof(LeKatsuDb))]
    [Migration("20260321123618_MakeRemarksNullable")]
    partial class MakeRemarksNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LeKatsuMNL.Models.AdminAccount", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("ContactNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Privileges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ManagerId");

                    b.ToTable("AdminAccounts");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.AdminArchive", b =>
                {
                    b.Property<int>("AaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AaId"));

                    b.Property<string>("ContactNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Privileges")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AaId");

                    b.ToTable("AdminArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchLocation", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("BranchLocationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("IslandGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("BranchId");

                    b.ToTable("BranchLocations");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchLocationArchive", b =>
                {
                    b.Property<int>("BlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlaId"));

                    b.Property<string>("Barangay")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("BranchLocationAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CityMunicipality")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IslandGroup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("BlaId");

                    b.ToTable("BranchLocationArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchManager", b =>
                {
                    b.Property<int>("BManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BManagerId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BManagerId");

                    b.HasIndex("BranchId")
                        .IsUnique();

                    b.ToTable("BranchManagers");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchManagerArchive", b =>
                {
                    b.Property<int>("BmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BmaId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BmaId");

                    b.ToTable("BranchManagerArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashAdded", b =>
                {
                    b.Property<int>("CshAddId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CshAddId"));

                    b.Property<decimal>("AddedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CrId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CshAddId");

                    b.HasIndex("CrId");

                    b.ToTable("CashAddeds");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashExpense", b =>
                {
                    b.Property<int>("CshExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CshExpId"));

                    b.Property<int>("CrId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExpenseAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CshExpId");

                    b.HasIndex("CrId");

                    b.HasIndex("ExpenseId");

                    b.ToTable("CashExpenses");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashRegister", b =>
                {
                    b.Property<int>("CrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CrId"));

                    b.Property<decimal?>("AddedCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CashSales")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NonCashExpenses")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StartingCash")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CrId");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("SubCategoryNames")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CommissaryArchive", b =>
                {
                    b.Property<int>("CaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ComId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsRepack")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SkuId")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("Yield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CaId");

                    b.ToTable("CommissaryArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CommissaryInventory", b =>
                {
                    b.Property<int>("ComId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepack")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ReorderValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SkuId")
                        .HasColumnType("int");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("Yield")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SkuId")
                        .IsUnique()
                        .HasFilter("[SkuId] IS NOT NULL");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("CommissaryInventories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ExpenseType", b =>
                {
                    b.Property<int>("ExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExpenseId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ExpenseId");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.IngredientRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecipeId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ParentId");

                    b.ToTable("IngredientRecipes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.InvTransactionType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TypeId");

                    b.ToTable("InvTransactionTypes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int>("ComId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<decimal>("QuantityChange")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ComId");

                    b.HasIndex("TypeId");

                    b.ToTable("InventoryTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VerifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ItemCategory", b =>
                {
                    b.Property<int>("ItemCtgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemCtgId"));

                    b.Property<string>("ItemCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ItemCtgId");

                    b.ToTable("ItemCategories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ItemTranArchive", b =>
                {
                    b.Property<int>("ItaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItaId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTranId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("ItaId");

                    b.ToTable("ItemTranArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ItemTransaction", b =>
                {
                    b.Property<int>("ItemTranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemTranId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("ItemTranId");

                    b.HasIndex("ItemId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ItemTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int?>("AdminAccountId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex("AdminAccountId");

                    b.HasIndex("BranchManagerId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderComments");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderInfo", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("BranchManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId");

                    b.HasIndex("BranchManagerId");

                    b.ToTable("OrderInfos");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderList", b =>
                {
                    b.Property<int>("ListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListId"));

                    b.Property<int?>("ComId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SkuId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ListId");

                    b.HasIndex("ComId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SkuId");

                    b.ToTable("OrderLists");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderListArchive", b =>
                {
                    b.Property<int>("OlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OlaId"));

                    b.Property<int>("ComId")
                        .HasColumnType("int");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OlaId");

                    b.ToTable("OrderListArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RejectItem", b =>
                {
                    b.Property<int>("RejectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RejectId"));

                    b.Property<int?>("ComId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SkuId")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RejectId");

                    b.HasIndex("ComId");

                    b.HasIndex("SkuId");

                    b.ToTable("RejectItems");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ResItemsArchive", b =>
                {
                    b.Property<int>("RiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RiaId"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ItemCategory")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("ItemImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("VatExempt")
                        .HasColumnType("bit");

                    b.HasKey("RiaId");

                    b.ToTable("ResItemsArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ResTransactionType", b =>
                {
                    b.Property<int>("TtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TtId"));

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TtId");

                    b.ToTable("ResTransactionTypes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantArchive", b =>
                {
                    b.Property<int>("RaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaId"));

                    b.Property<decimal?>("AddedStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeginningStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DeductedStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ResId")
                        .HasColumnType("int");

                    b.Property<int>("StaffInputted")
                        .HasColumnType("int");

                    b.HasKey("RaId");

                    b.ToTable("RestaurantArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantInventory", b =>
                {
                    b.Property<int>("ResId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResId"));

                    b.Property<decimal?>("AddedStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BeginningStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DeductedStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("ResId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StaffId");

                    b.ToTable("RestaurantInventories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<int>("ItemCtgId")
                        .HasColumnType("int");

                    b.Property<string>("ItemImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("VatExempt")
                        .HasColumnType("bit");

                    b.HasKey("ItemId");

                    b.HasIndex("ItemCtgId");

                    b.ToTable("RestaurantItems");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiptNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TtId")
                        .HasColumnType("int");

                    b.HasKey("TransactionId");

                    b.HasIndex("StaffId");

                    b.HasIndex("TtId");

                    b.ToTable("RestaurantTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.STimeArchive", b =>
                {
                    b.Property<int>("StaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("TimeId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("StaId");

                    b.ToTable("STimeArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuArchive", b =>
                {
                    b.Property<int>("SaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReorderLevelEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSellingPriceEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackagingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SaId");

                    b.ToTable("SkuArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuHeader", b =>
                {
                    b.Property<int>("SkuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkuId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReorderLevelEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSellingPriceEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PackagingUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SkuId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("SkuHeaders");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("ComId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SkuId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetSkuId")
                        .HasColumnType("int");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RecipeId");

                    b.HasIndex("ComId");

                    b.HasIndex("SkuId");

                    b.HasIndex("TargetSkuId");

                    b.ToTable("SkuRecipes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.StaffArchive", b =>
                {
                    b.Property<int>("AsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsId"));

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AsId");

                    b.ToTable("StaffArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.StaffInformation", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("ContactNum")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StaffId");

                    b.ToTable("StaffInformations");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.StaffTimeSlot", b =>
                {
                    b.Property<int>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TimeIn")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("TimeOut")
                        .HasColumnType("time");

                    b.HasKey("TimeId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffTimeSlots");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SubBranchOrderArchive", b =>
                {
                    b.Property<int>("SboId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SboId"));

                    b.Property<int>("BManagerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SboId");

                    b.ToTable("SubBranchOrderArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SubCategory", b =>
                {
                    b.Property<int>("SubCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubCategoryId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SubCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubCategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyHistory", b =>
                {
                    b.Property<int>("SHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SHistoryId"));

                    b.Property<int>("SupplyId")
                        .HasColumnType("int");

                    b.HasKey("SHistoryId");

                    b.HasIndex("SupplyId");

                    b.ToTable("SupplyHistories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyHistoryArchive", b =>
                {
                    b.Property<int>("ShaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShaId"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SHistoryId")
                        .HasColumnType("int");

                    b.Property<int>("SListId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int");

                    b.HasKey("ShaId");

                    b.ToTable("SupplyHistoryArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyList", b =>
                {
                    b.Property<int>("SListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SListId"));

                    b.Property<int>("ComId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("SListId");

                    b.HasIndex("ComId");

                    b.HasIndex("SupplyId");

                    b.ToTable("SupplyLists");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyListArchive", b =>
                {
                    b.Property<int>("SlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlaId"));

                    b.Property<int>("ComId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SListId")
                        .HasColumnType("int");

                    b.Property<int>("SupplyId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SlaId");

                    b.ToTable("SupplyListArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyOrder", b =>
                {
                    b.Property<int>("SoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoaId"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ReceiptImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("SoaId");

                    b.HasIndex("VendorId");

                    b.ToTable("SupplyOrders");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyOrderArchive", b =>
                {
                    b.Property<int>("SoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoaId"));

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SListId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("SoaId");

                    b.HasIndex("VendorId");

                    b.ToTable("SupplyOrderArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.TransactionArchive", b =>
                {
                    b.Property<int>("RtaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RtaId"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<int>("ItemTranId")
                        .HasColumnType("int");

                    b.Property<string>("ReceiptNum")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.HasKey("RtaId");

                    b.ToTable("TransactionArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.VendorArchive", b =>
                {
                    b.Property<int>("VaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VaId"));

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondVendorCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondVendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SupplierType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VaId");

                    b.ToTable("VendorArchives");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.VendorInfo", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<string>("CompanyAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("SecondVendorCn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondVendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SupplierType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("VendorId");

                    b.ToTable("VendorInfos");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchManager", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.BranchLocation", "BranchLocation")
                        .WithOne("BranchManager")
                        .HasForeignKey("LeKatsuMNL.Models.BranchManager", "BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchLocation");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashAdded", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CashRegister", "CashRegister")
                        .WithMany("CashAddeds")
                        .HasForeignKey("CrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CashRegister");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashExpense", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CashRegister", "CashRegister")
                        .WithMany("CashExpensesList")
                        .HasForeignKey("CrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.ExpenseType", "ExpenseType")
                        .WithMany("CashExpenses")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashRegister");

                    b.Navigation("ExpenseType");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CommissaryInventory", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.Category", "Category")
                        .WithMany("CommissaryInventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.SkuHeader", "SkuHeader")
                        .WithOne("CommissaryInventory")
                        .HasForeignKey("LeKatsuMNL.Models.CommissaryInventory", "SkuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.VendorInfo", "Vendor")
                        .WithMany("CommissaryInventories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("SkuHeader");

                    b.Navigation("SubCategory");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.IngredientRecipe", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "Parent")
                        .WithMany("IngredientRecipes")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.InventoryTransaction", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "CommissaryInventory")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.InvTransactionType", "InvTransactionType")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommissaryInventory");

                    b.Navigation("InvTransactionType");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.Invoice", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.OrderInfo", "OrderInfo")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrderInfo");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ItemTransaction", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.RestaurantItem", "RestaurantItem")
                        .WithMany("ItemTransactions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.RestaurantTransaction", "RestaurantTransaction")
                        .WithMany("ItemTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RestaurantItem");

                    b.Navigation("RestaurantTransaction");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderComment", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.AdminAccount", "AdminAccount")
                        .WithMany()
                        .HasForeignKey("AdminAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.BranchManager", "BranchManager")
                        .WithMany("OrderComments")
                        .HasForeignKey("BranchManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.OrderInfo", "OrderInfo")
                        .WithMany("OrderComments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminAccount");

                    b.Navigation("BranchManager");

                    b.Navigation("OrderInfo");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderInfo", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.BranchManager", "BranchManager")
                        .WithMany("Orders")
                        .HasForeignKey("BranchManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BranchManager");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderList", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "CommissaryInventory")
                        .WithMany("OrderLists")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.OrderInfo", "OrderInfo")
                        .WithMany("OrderLists")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.SkuHeader", "SkuHeader")
                        .WithMany("OrderLists")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissaryInventory");

                    b.Navigation("OrderInfo");

                    b.Navigation("SkuHeader");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RejectItem", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "CommissaryInventory")
                        .WithMany("RejectItems")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.SkuHeader", "SkuHeader")
                        .WithMany("RejectItems")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissaryInventory");

                    b.Navigation("SkuHeader");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantInventory", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.Category", "Category")
                        .WithMany("RestaurantInventories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.StaffInformation", "StaffInputted")
                        .WithMany("RestaurantInventories")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("StaffInputted");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantItem", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.ItemCategory", "ItemCategory")
                        .WithMany("RestaurantItems")
                        .HasForeignKey("ItemCtgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemCategory");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantTransaction", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.StaffInformation", "Staff")
                        .WithMany("RestaurantTransactions")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.ResTransactionType", "ResTransactionType")
                        .WithMany("RestaurantTransactions")
                        .HasForeignKey("TtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResTransactionType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuHeader", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuRecipe", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "CommissaryInventory")
                        .WithMany("SkuRecipes")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LeKatsuMNL.Models.SkuHeader", "SkuHeader")
                        .WithMany("SkuRecipes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.SkuHeader", "TargetSku")
                        .WithMany()
                        .HasForeignKey("TargetSkuId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CommissaryInventory");

                    b.Navigation("SkuHeader");

                    b.Navigation("TargetSku");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.StaffTimeSlot", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.StaffInformation", "Staff")
                        .WithMany("StaffTimeSlots")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SubCategory", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyHistory", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.SupplyOrder", "SupplyOrder")
                        .WithMany("SupplyHistories")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupplyOrder");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyList", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.CommissaryInventory", "CommissaryInventory")
                        .WithMany("SupplyLists")
                        .HasForeignKey("ComId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeKatsuMNL.Models.SupplyOrder", "SupplyOrder")
                        .WithMany("SupplyLists")
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommissaryInventory");

                    b.Navigation("SupplyOrder");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyOrder", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.VendorInfo", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyOrderArchive", b =>
                {
                    b.HasOne("LeKatsuMNL.Models.VendorInfo", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchLocation", b =>
                {
                    b.Navigation("BranchManager");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.BranchManager", b =>
                {
                    b.Navigation("OrderComments");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CashRegister", b =>
                {
                    b.Navigation("CashAddeds");

                    b.Navigation("CashExpensesList");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.Category", b =>
                {
                    b.Navigation("CommissaryInventories");

                    b.Navigation("RestaurantInventories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.CommissaryInventory", b =>
                {
                    b.Navigation("IngredientRecipes");

                    b.Navigation("InventoryTransactions");

                    b.Navigation("OrderLists");

                    b.Navigation("RejectItems");

                    b.Navigation("SkuRecipes");

                    b.Navigation("SupplyLists");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ExpenseType", b =>
                {
                    b.Navigation("CashExpenses");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.InvTransactionType", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ItemCategory", b =>
                {
                    b.Navigation("RestaurantItems");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.OrderInfo", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderComments");

                    b.Navigation("OrderLists");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.ResTransactionType", b =>
                {
                    b.Navigation("RestaurantTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantItem", b =>
                {
                    b.Navigation("ItemTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.RestaurantTransaction", b =>
                {
                    b.Navigation("ItemTransactions");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SkuHeader", b =>
                {
                    b.Navigation("CommissaryInventory")
                        .IsRequired();

                    b.Navigation("OrderLists");

                    b.Navigation("RejectItems");

                    b.Navigation("SkuRecipes");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.StaffInformation", b =>
                {
                    b.Navigation("RestaurantInventories");

                    b.Navigation("RestaurantTransactions");

                    b.Navigation("StaffTimeSlots");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.SupplyOrder", b =>
                {
                    b.Navigation("SupplyHistories");

                    b.Navigation("SupplyLists");
                });

            modelBuilder.Entity("LeKatsuMNL.Models.VendorInfo", b =>
                {
                    b.Navigation("CommissaryInventories");
                });
#pragma warning restore 612, 618
        }
    }
}
